package com.skycraft.atmosphere;

import com.skycraft.Skycraft;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * Extra soundtrack events (the situational ones such as {@code music.combat} are registered by
 * {@link com.skycraft.world.WorldSounds}). All of them point at the original Skycraft score in
 * {@code assets/skycraft/sounds/music/}, generated by {@code tools/music/compose.py}.
 */
public final class AtmosphereSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, Skycraft.MODID);

    /** Dragon / boss battle piece. Also part of the {@code music.combat} pool (referenced as an event in sounds.json). */
    public static final RegistryObject<SoundEvent> MUSIC_BOSS = register("music.boss");
    /** Three-second level-up fanfare, played by {@link com.skycraft.atmosphere.client.AtmosphereClientEvents}. */
    public static final RegistryObject<SoundEvent> MUSIC_LEVEL_UP = register("music.level_up");

    private AtmosphereSounds() {}

    private static RegistryObject<SoundEvent> register(String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(new ResourceLocation(Skycraft.MODID, name)));
    }

    static void init(IEventBus modBus) {
        SOUNDS.register(modBus);
    }
}
