package com.skycraft.arsenal;

import com.skycraft.Skycraft;
import com.skycraft.arsenal.item.ArrowKind;
import com.skycraft.arsenal.item.ArtifactAxeItem;
import com.skycraft.arsenal.item.ArtifactBowItem;
import com.skycraft.arsenal.item.ArtifactItem;
import com.skycraft.arsenal.item.ArtifactMeleeItem;
import com.skycraft.arsenal.item.ArtifactStaffItem;
import com.skycraft.arsenal.item.SkyArrowItem;
import com.skycraft.arsenal.item.SkyCrossbowItem;
import com.skycraft.arsenal.item.SpellbreakerItem;
import com.skycraft.arsenal.item.StaffItem;
import com.skycraft.arsenal.item.StaffKind;
import com.skycraft.crafting.SmithingTier;
import com.skycraft.crafting.WeaponType;
import net.minecraft.util.RandomSource;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Rarity;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * Every arsenal item: Skyrim arrows and bolts, Dawnguard crossbows, staves and the named artifacts.
 * Gold values and weights ship in {@code data/skycraft/skycraft_values/arsenal.json} and
 * {@code data/skycraft/skycraft_weights/arsenal.json} (generated by {@code tools/textures/arsenal.py}).
 */
public final class ArsenalItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Skycraft.MODID);

    public static final Map<ArrowKind, RegistryObject<Item>> ARROWS = new EnumMap<>(ArrowKind.class);
    public static final Map<StaffKind, RegistryObject<Item>> STAVES = new EnumMap<>(StaffKind.class);
    /** Every artifact, in registration order. */
    public static final List<RegistryObject<Item>> ARTIFACTS = new ArrayList<>();

    static {
        for (ArrowKind kind : ArrowKind.VALUES) {
            ARROWS.put(kind, ITEMS.register(kind.id, () -> new SkyArrowItem(kind, new Item.Properties().rarity(kind.rarity))));
        }
    }

    // ------------------------------------------------------------------ crossbows
    public static final RegistryObject<Item> IMPERIAL_CROSSBOW = ITEMS.register("imperial_crossbow",
            () -> new SkyCrossbowItem(0.6f, 0.5f, new Item.Properties().durability(500)));
    public static final RegistryObject<Item> ENHANCED_CROSSBOW = ITEMS.register("enhanced_crossbow",
            () -> new SkyCrossbowItem(1.0f, 0.5f, new Item.Properties().durability(650)));
    public static final RegistryObject<Item> DWARVEN_CROSSBOW = ITEMS.register("dwarven_crossbow",
            () -> new SkyCrossbowItem(1.2f, 0.5f, new Item.Properties().durability(800).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ENHANCED_DWARVEN_CROSSBOW = ITEMS.register("enhanced_dwarven_crossbow",
            () -> new SkyCrossbowItem(1.6f, 0.6f, new Item.Properties().durability(1000).rarity(Rarity.UNCOMMON)));

    public static final List<RegistryObject<Item>> CROSSBOWS = List.of(IMPERIAL_CROSSBOW, ENHANCED_CROSSBOW, DWARVEN_CROSSBOW, ENHANCED_DWARVEN_CROSSBOW);

    // ------------------------------------------------------------------ staves
    static {
        for (StaffKind kind : StaffKind.values()) {
            RegistryObject<Item> staff = ITEMS.register(kind.id, () -> kind.artifact()
                    ? new ArtifactStaffItem(kind, new Item.Properties().rarity(Rarity.EPIC))
                    : new StaffItem(kind, new Item.Properties().rarity(Rarity.UNCOMMON)));
            STAVES.put(kind, staff);
            if (kind.artifact()) ARTIFACTS.add(staff);
        }
    }

    // ------------------------------------------------------------------ artifacts
    public static final RegistryObject<Item> DAWNBREAKER = melee("dawnbreaker", SmithingTier.EBONY, WeaponType.SWORD);
    public static final RegistryObject<Item> CHILLREND = melee("chillrend", SmithingTier.GLASS, WeaponType.SWORD);
    public static final RegistryObject<Item> MEHRUNES_RAZOR = melee("mehrunes_razor", SmithingTier.DAEDRIC, WeaponType.DAGGER);
    public static final RegistryObject<Item> DRAGONBANE = melee("dragonbane", SmithingTier.EBONY, WeaponType.SWORD);
    public static final RegistryObject<Item> VOLENDRUNG = melee("volendrung", SmithingTier.EBONY, WeaponType.WARHAMMER);
    public static final RegistryObject<Item> EBONY_BLADE = melee("ebony_blade", SmithingTier.EBONY, WeaponType.GREATSWORD);
    public static final RegistryObject<Item> MACE_OF_MOLAG_BAL = melee("mace_of_molag_bal", SmithingTier.DAEDRIC, WeaponType.MACE);
    public static final RegistryObject<Item> BLOODSKAL_BLADE = melee("bloodskal_blade", SmithingTier.GLASS, WeaponType.GREATSWORD);
    public static final RegistryObject<Item> WINDSHEAR = melee("windshear", SmithingTier.ELVEN, WeaponType.SWORD);
    public static final RegistryObject<Item> WUUTHRAD = artifact("wuuthrad",
            () -> new ArtifactAxeItem("wuuthrad", SmithingTier.EBONY, WeaponType.BATTLEAXE, artifactProps(SmithingTier.EBONY)));
    public static final RegistryObject<Item> AURIELS_BOW = bow("auriels_bow", SmithingTier.ELVEN);
    public static final RegistryObject<Item> NIGHTINGALE_BOW = bow("nightingale_bow", SmithingTier.EBONY);
    public static final RegistryObject<Item> ZEPHYR = bow("zephyr", SmithingTier.DWARVEN);
    public static final RegistryObject<Item> BOW_OF_SHADOWS = bow("bow_of_shadows", SmithingTier.ELVEN);
    public static final RegistryObject<Item> SPELLBREAKER = artifact(SpellbreakerItem.ID,
            () -> new SpellbreakerItem(new Item.Properties().durability(ArtifactItem.DURABILITY).rarity(Rarity.EPIC)));

    public static final List<RegistryObject<Item>> ARTIFACT_BOWS = List.of(AURIELS_BOW, NIGHTINGALE_BOW, ZEPHYR, BOW_OF_SHADOWS);

    private ArsenalItems() {}

    private static Item.Properties artifactProps(SmithingTier tier) {
        Item.Properties props = new Item.Properties().durability(ArtifactItem.DURABILITY).rarity(Rarity.EPIC);
        if (tier.fireResistant) props.fireResistant();
        return props;
    }

    private static RegistryObject<Item> melee(String id, SmithingTier tier, WeaponType type) {
        return artifact(id, () -> new ArtifactMeleeItem(id, tier, type, artifactProps(tier)));
    }

    private static RegistryObject<Item> bow(String id, SmithingTier tier) {
        return artifact(id, () -> new ArtifactBowItem(id, tier, artifactProps(tier)));
    }

    private static RegistryObject<Item> artifact(String id, java.util.function.Supplier<Item> factory) {
        RegistryObject<Item> obj = ITEMS.register(id, factory);
        ARTIFACTS.add(obj);
        return obj;
    }

    // ------------------------------------------------------------------ lookups

    public static Item arrow(ArrowKind kind) {
        return ARROWS.get(kind).get();
    }

    public static Item staff(StaffKind kind) {
        return STAVES.get(kind).get();
    }

    public static List<RegistryObject<Item>> artifacts() {
        return Collections.unmodifiableList(ARTIFACTS);
    }

    /** A random artifact (for quest rewards). */
    public static ItemStack randomArtifact(RandomSource random) {
        return new ItemStack(ARTIFACTS.get(random.nextInt(ARTIFACTS.size())).get());
    }
}
