name = "Skycraft"
author = "Skycraft Team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ab62dbed9c4d733ad52f3e06dff0d950845e60c9e135cc2de8884cccb39c417"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
