name = "Skycraft"
author = "Skycraft Team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2dbadc32641233c8f58c04cf6d97969ac0108aab253f06f30327b7e934528c7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
