name = "Skycraft"
author = "Skycraft Team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3090fae152addaff5e1b7ae9f3c1d012a4377694f0f8a085101067cb06a53ff4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
